<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Anton
 * Date: 14.12.13
 * Time: 17:26
 * To change this template use File | Settings | File Templates.
 */

class AjaxServerResponse
{
    public $code;
    public $userMessage;
    public $moreInfoUri;
    public $data;

    function __construct($code, $message, $url, $data = null)
    {
        $this->code = $code;
        $this->userMessage = $message;
        $this->moreInfoUri = $url;
        $this->data = $data;
    }
}