<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Anton
 * Date: 21.03.15
 * Time: 22:02
 * To change this template use File | Settings | File Templates.
 */

require_once("WebServBase.module");
require_once("Headers.module");
require_once("Contract.module");

class CalculateRouteWebService extends WebServBase
{

    public function onGet($args)
    {
        // TODO: получаем данные созданного маршрута

    }

    public function onPost($args, $data)
    {
        // TODO: пересчитываем данные маршрута




    }

    public function onPut($args, $data)
    {





    }

    public function onDelete($args, $data)
    {


    }



}