<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Anton
 * Date: 09.03.15
 * Time: 16:03
 * To change this template use File | Settings | File Templates.
 */
require_once("WebServBase.module");
require_once("Headers.module");
require_once("Contract.module");

class CargoSelectedWebService extends WebServBase
{

    public function onGet($args)
    {
        /*
         * Возвращаем список выбранных задач для пользователя
         *
         * */


        $accountId = null;
        $userTokenId = Cookies::getUserTokenId();

        // если пользователь авторизован, то получаем ID акаунта
        if(true == CurrentUser::isAuthenticated())
        {
            $accountId = CurrentUser::getUserId();
        }

        // возвращаем объекты AjaxTask
        $db = SqlFactory::getSql();

        try
        {
            $page_arg = intval($args[0]);
            $page = $page_arg > 0 ? $page_arg : 1;

            // TODO Сделать проверку правильности номера страницы полученного с клиента

            $limit = 20;
            $offset = ($page - 1) * $limit;
            $allRowCount = 0;

            // получаем количество записей удовлетворяющих условию фильтрации
            $sql = 'SELECT count(C.id)
                    FROM cargo C
                      INNER JOIN cargo_selected CS
                            ON CS.cargo_id = C.id
                              AND (CS.account_id = ?i OR CS.user_token_id = ?i)
                    WHERE C.is_deleted = 0';

            $allRowCount = $db->getOne($sql, $accountId, $userTokenId);


            $sql = 'SELECT C.id, GC1.name AS city1, GC2.name AS city2, CT.name AS type,
                          C.weight, C.value, C.distance, C.cost, C.ready_date
                    FROM cargo C
                        INNER JOIN geocities GC1
                            ON GC1.id = C.city1_id
                        INNER JOIN geocities GC2
                            ON GC2.id = C.city2_id
                        INNER JOIN cargo_type CT
                            ON CT.id = C.cargo_type_id
                        INNER JOIN cargo_selected CS
                            ON CS.cargo_id = C.id
                              AND (CS.account_id = ?i OR CS.user_token_id = ?i)
                    WHERE C.is_deleted = 0';

            $result = $db->query($sql, $accountId, $userTokenId);
            $arr = array();

            if(0 < $db->numRows($result))
            {
                $arr = array();

                while($row = $db->fetch($result))
                {
                    $rusReadyDate = Validators::convertMySqlDate2RusDate($row['ready_date']);

                    $entry = new AjaxTask
                    (
                        $row['id'], $row['city1'], $row['city2'], $row['type'], $row['weight'], $row['value'], $row['distance'], $row['cost'], $rusReadyDate, false, false
                    );

                    array_push($arr, $entry);
                }
            }

            // на данный момент информацию о страницах не заполняем, т.к. возвращаем все данные
            $respData = new AjaxTaskList();
            $respData->offset = $offset;
            $respData->limit = $limit;
            $respData->allRowCount = $allRowCount;
            $respData->page = $page;
            $respData->tasks = $arr;

            $response = new AjaxServerResponse(200, '', '', $respData);
            sendHTTPStatus(200);
            header('Content-type: application/json');
            echo json_encode($response);

        }
        catch(Exception $ex)
        {
            Log::writeSqlExeption($db, $ex);
            $this->returnError(500, array(1));
        }
    }

    public function onPost($args, $data)
    {
        // AjaxTaskInfoList
        // AjaxTaskInfo

        $accountId = null;
        $userTokenId = Cookies::getUserTokenId();

        // если пользователь авторизован, то получаем ID акаунта
        if(true == CurrentUser::isAuthenticated())
        {
            $accountId = CurrentUser::getUserId();
        }

        $db = SqlFactory::getSql();

        try
        {
            if(is_null($accountId))
                $check_sql_definition = $db->parse(' AND user_token_id = ?i ', $userTokenId);
            else
                $check_sql_definition = $db->parse(' AND account_id = ?i ', $accountId);

            foreach($data->tasks as $task)
            {
                // страхуемся от внесения дублей в таблицу выбранных грузов
                $sql = 'SELECT id FROM cargo_selected WHERE cargo_id = ?i ?p';
                $result = $db->getOne($sql, $task->taskId, $check_sql_definition);

                if(empty($result))
                {
                    // вносим новую запись в таблицу выбранных грузов
                    $sql = 'INSERT INTO cargo_selected (cargo_id, account_id, user_token_id) VALUES ?p';

                    if(is_null($accountId))
                        $insert_sql_definition = $db->parse(' (?i, null, ?i) ', $task->taskId, $userTokenId);
                    else
                        $insert_sql_definition = $db->parse(' (?i, ?i, null) ', $task->taskId, $accountId);

                    $db->query($sql, $insert_sql_definition);
                }
            }


            $response = new AjaxServerResponse(200, '', '', $data);
            sendHTTPStatus(200);
            header('Content-type: application/json');
            echo json_encode($response);

        }
        catch(Exception $ex)
        {
            Log::writeSqlExeption($db, $ex);
            $this->returnError(500, array(1), $data);
        }
    }

    public function onPut($args, $data)
    {
        // HTTP/1.1 405 Method Not Allowed
        sendHTTPStatus(405);
        header('Allow: GET,POST,DELETE');
    }

    public function onDelete($args, $data)
    {
        // AjaxTaskInfoList
        // AjaxTaskInfo

        $accountId = null;
        $userTokenId = Cookies::getUserTokenId();

        // если пользователь авторизован, то получаем ID акаунта
        if(true == CurrentUser::isAuthenticated())
        {
            $accountId = CurrentUser::getUserId();
        }

        $db = SqlFactory::getSql();

        try
        {
            if(is_null($accountId))
                $where_sql_definition = $db->parse(' AND user_token_id = ?i ', $userTokenId);
            else
                $where_sql_definition = $db->parse(' AND account_id = ?i ', $accountId);

            foreach($data->tasks as $task)
            {
                // удаляем запись из таблицы выбранных грузов
                $sql = 'DELETE FROM cargo_selected WHERE cargo_id = ?i ?p';

                $db->query($sql, $task->taskId, $where_sql_definition);
            }


            $response = new AjaxServerResponse(200, '', '', $data);
            sendHTTPStatus(200);
            header('Content-type: application/json');
            echo json_encode($response);

        }
        catch(Exception $ex)
        {
            Log::writeSqlExeption($db, $ex);
            $this->returnError(500, array(1), $data);
        }
    }



    public static function mapSelectedCargoToAccount($accountId)
    {
        $userTokenId = Cookies::getUserTokenId();
        $db = SqlFactory::getSql();

        try
        {
            // 1. Удаляем дубли выбора грузов

            // ... получаем идентификаторы строк для удаления
            $sql = 'SELECT CS_UT.id
                    FROM cargo_selected CS_UT
                        INNER JOIN cargo_selected CS_AC
                            ON CS_UT.cargo_id = CS_AC.cargo_id
                                AND CS_UT.user_token_id = ?i
                                AND CS_AC.account_id = ?i';

            $result = $db->query($sql, $userTokenId, $accountId);

            if(0 < $db->numRows($result))
            {
               $arr_ids = array();

               // ... собираем полученные идентификаторы
               while($row = $db->fetch($result))
               {
                   array_push($arr_ids, $row['id']);
               }

                // ... удаляем дубли строк из таблицы
               if(0 < count($arr_ids))
               {
                   $in_sql_definition = implode(',', $arr_ids);
                   $sql = 'DELETE FROM cargo_selected WHERE id IN(' . $in_sql_definition . ')';
                   $db->query($sql);
               }
            }

            // 2. Обновляем запись о выбранном грузе - назначаем владельцем записи акаунт пользователя
            $sql = 'UPDATE cargo_selected SET user_token_id = null, account_id=?i WHERE user_token_id=?i';
            $db->query($sql, $accountId, $userTokenId);
        }
        catch(Exception $ex)
        {
            Log::writeSqlExeption($db, $ex);
        }
    }
}