<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Anton
 * Date: 20.11.13
 * Time: 1:08
 * To change this template use File | Settings | File Templates.
 */

/*
 * Возвращаем объект web сервиса по его имени
 * */
require_once("CargoWebService.module");
require_once("VehicleWebService.module");
require_once("AccountWebService.module");
require_once("AuthWebService.module");
require_once("OrgWebService.module");
require_once("DictWebService.module");
require_once("CityAutoCompleteWebService.module");
require_once("Validators.module");
require_once("AppErrors.module");
require_once("SqlFactory.module");
require_once("SearchTasksWebService.module");
require_once("CargoSelectedWebService.module");
require_once("CalculateRouteWebService.module");
require_once("RouteWebService.module");
require_once("RouteExtWebService.module");
require_once("VehicleParamsWebService.module");




function getWebService($name)
{
    if("cargo" == $name)
        return new CargoWebService();
    else if ("vehicle" == $name)
        return new VehicleWebService();
    else if("account" == $name)
        return new AccountWebService();
    else if("auth" == $name)
        return new AuthWebService();
    else if("org" == $name)
        return new OrgWebService();
    else if("dict" == $name)
        return new DictWebService();
    else if("cityautocomplete" == $name)
        return new CityAutoCompleteWebService();
    else if("searchtasks" == $name)
        return new SearchTasksWebService();
    else if("caregoselected" == $name)
        return new CargoSelectedWebService();
    else if("calculateroute" == $name)
        return new CalculateRouteWebService();
    else if("route" == $name)
        return new RouteWebService();
    else if("routeext" == $name)
        return new RouteExtWebService();
    else if("vehicleparams" == $name)
        return new VehicleParamsWebService();

    return null;
}