<?php

    require_once(ROUTE_CALCULATOR_PATH . "/GObject.module");
    require_once(ROUTE_CALCULATOR_PATH . "/Ant.module");
    require_once(ROUTE_CALCULATOR_PATH . "/ConflictResolveCriteria.module");
    require_once(ROUTE_CALCULATOR_PATH . "/GEdge.module");
    require_once(ROUTE_CALCULATOR_PATH . "/GEOEllipse.module");
    require_once(ROUTE_CALCULATOR_PATH . "/GEOPoint.module");
    require_once(ROUTE_CALCULATOR_PATH . "/GVertex.module");
    require_once(ROUTE_CALCULATOR_PATH . "/GVertexTaskRole.module");
    require_once(ROUTE_CALCULATOR_PATH . "/LoadingStrategy.module");
    require_once(ROUTE_CALCULATOR_PATH . "/Route.module");
    require_once(ROUTE_CALCULATOR_PATH . "/RouteCalculator.module");
    require_once(ROUTE_CALCULATOR_PATH . "/RouteEntry.module");
    require_once(ROUTE_CALCULATOR_PATH . "/RouteRestrictions.module");
    require_once(ROUTE_CALCULATOR_PATH . "/RouteTask.module");
    require_once(ROUTE_CALCULATOR_PATH . "/RouteTaskList.module");
    require_once(ROUTE_CALCULATOR_PATH . "/UndirectedGraph.module");

?>
