<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Anton
 * Date: 21.03.15
 * Time: 22:02
 * To change this template use File | Settings | File Templates.
 */

require_once("WebServBase.module");
require_once("Headers.module");
require_once("Contract.module");
require_once("RouteHelper.module");
require_once("CargoSelectedHelper.module");
require_once(ROUTE_CALCULATOR_PATH . "/RouteCalculatorIncludes.inc");

class CalculateRouteWebService extends WebServBase
{

    public function onGet($args)
    {
        // получаем данные созданного маршрута
        $accountId = null;
        $userTokenId = null;
        CurrentUser::FillUserIdentities($accountId, $userTokenId);

        $db = SqlFactory::getSql();

        try
        {
            $routePointList = self::GetRouteData($accountId, $userTokenId, $db);
            $cities = RouteHelper::GetUniqueStartCitiesFromAjaxRoutePointsArray($routePointList->routePoints);
            $citiesList = new AjaxCityList($cities);

            $responseData = new AjaxRoutePointListAndCitiesList();
            $responseData->routePointList = $routePointList;
            $responseData->routeStartCitiesList = $citiesList;
            $response = new AjaxServerResponse(200, '', '', $responseData);
            sendHTTPStatus(200);
            header('Content-type: application/json');
            echo json_encode($response);

        }
        catch(Exception $ex)
        {
            Log::writeSqlExeption($db, $ex);
            $this->returnError(500, array(1));
        }
    }

    public function onPost($args, $data)
    {
        // пересчитываем данные маршрута
        $accountId = null;
        $userTokenId = null;
        CurrentUser::FillUserIdentities($accountId, $userTokenId);

        // TODO убрать после отладки
        //$userTokenId = 1;

        $db = SqlFactory::getSql();

        try
        {
            // AjaxCalculateOptions
            $options = $data;

            // 1. пересчитываем маршрут
            $route = self::CalculateRoute($accountId, $userTokenId, $options, $db);

            // 2. обновляем маршрут пользователя
            self::UpdateRoute($accountId, $userTokenId, $options, $route, $db);

            // 3. получаем данные марщрута
            $routePointList = self::GetRouteData($accountId, $userTokenId, $db);

            // 4. получаем список городов маршрута
            $cities = RouteHelper::GetUniqueStartCitiesFromAjaxRoutePointsArray($routePointList->routePoints);
            $citiesList = new AjaxCityList($cities);

            // 5. возвращаем данные клиенту
            $responseData = new AjaxRoutePointListAndCitiesList();
            $responseData->routePointList = $routePointList;
            $responseData->routeStartCitiesList = $citiesList;

            $response = new AjaxServerResponse(200, '', '', $responseData);
            sendHTTPStatus(200);
            header('Content-type: application/json');
            echo json_encode($response);

        }
        catch(Exception $ex)
        {
            Log::writeSqlExeption($db, $ex);
            $this->returnError(500, array(1));
        }
    }

    public function onPut($args, $data)
    {
        // HTTP/1.1 405 Method Not Allowed
        sendHTTPStatus(405);
        header('Allow: GET,POST');
    }

    public function onDelete($args, $data)
    {
        // HTTP/1.1 405 Method Not Allowed
        sendHTTPStatus(405);
        header('Allow: GET,POST');
    }

    static function GetRouteData($accountId, $userTokenId, $db)
    {
        $list = new AjaxRoutePointList();

        // 1. получаем идентификатор маршрута
        $routeId = RouteHelper::GetRouteId($accountId, $userTokenId, $db);

        // 2. получаем данные маршрута
        $sql = 'SELECT
                    RP.id AS route_point_id,
                    RP.type_id,
                    RP.distance AS route_point_distance,
                    RP.city_id AS route_point_city_id,
                    GC.name AS route_point_city_name,
                    CASE RP.type_id WHEN 1 THEN ifnull(C.weight, 0) ELSE (- ifnull(C.weight, 0)) END AS route_point_weight,
                    CASE RP.type_id WHEN 1 THEN ifnull(C.value, 0) ELSE (- ifnull(C.value, 0)) END AS route_point_value,
                    CASE RP.type_id WHEN 2 THEN ifnull(C.cost, 0) ELSE 0 END AS route_point_cost,
                    CASE RP.type_id WHEN 1 THEN ifnull(C.ready_date, 0) ELSE \'\' END AS route_point_ready_date,
                    ifnull(C.id, 0) AS cargo_id,
                    ifnull(C.is_deleted, 0) AS cargo_is_deleted,
                    ifnull(C.distance, 0) AS cargo_distance,
                    ifnull(C.weight, 0) AS cargo_weight,
                    ifnull(C.value, 0) AS cargo_value,
                    ifnull(C.cost, 0) AS cargo_cost
                FROM route_point RP
                    INNER JOIN geocities GC
                        ON GC.id = RP.city_id
                    LEFT OUTER JOIN cargo_selected CS
                        ON CS.id = RP.cargo_selected_id
                    LEFT OUTER JOIN cargo C
                        ON C.id = CS.cargo_id
                WHERE RP.route_id = ?i
                ORDER BY RP.order_num';

        $result = $db->query($sql, $routeId);

        if(0 < $db->numRows($result))
        {
            while($row = $db->fetch($result))
            {
                $isFirstPoint = (RoutePointType::FirstPoint == $row['type_id']) ? true : false;

                $entry = new AjaxRoutePoint
                (
                    $row['route_point_id'], $isFirstPoint, $row['route_point_city_id'], $row['route_point_city_name'],
                    $row['route_point_distance'], $row['route_point_weight'], $row['route_point_value'], $row['route_point_cost'], $row['route_point_ready_date'],
                    $row['cargo_id'], $row['cargo_is_deleted'], $row['cargo_distance'], $row['cargo_weight'], $row['cargo_value'], $row['cargo_cost']
                );

                array_push($list->routePoints, $entry);
            }
        }

        return $list;
    }


    static function CalculateRoute($accountId, $userTokenId, $options, $db)
    {
        // 1. получаем идентификатор маршрута
        $routeId = RouteHelper::GetRouteId($accountId, $userTokenId, $db);

        // 2. получаем данные маршрута - TaskInfo[] в зависимости от настроек пользователя
        if($options->useCargoFromRoute)
            $routeTasksInfoList = RouteHelper::GetCargoInRouteData($routeId, $db);
        else
            $routeTasksInfoList = CargoSelectedHelper::GetSelectedCargoData($accountId, $userTokenId, $db);


        //print_r($routeTasksInfoList);

        // 3. создаём список ограничений
        $conflictResolveCriteria = $options->conflictResolveCriteria == 'MaxProceeds' ? ConflictResolveCriteria::MaxProceeds : ConflictResolveCriteria::MaxProfit;
        $loadingStrategy = $options->loadingStrategy == 'SavingWeight' ? LoadingStrategy::SavingWeight : LoadingStrategy::SavingValue;
        $routeRestrictions = new RouteRestrictions($options->vehicleParams->maxValue, $options->vehicleParams->maxWeight, $conflictResolveCriteria, $loadingStrategy);

        // 4. создаём список заданий на перевозку - RouteTask, RouteTaskList
        $list = array();

        foreach($routeTasksInfoList as $routeTaskInfo)
        {
            $vertexA = new GVertex($routeTaskInfo->cityId1, $routeTaskInfo->city1Name, $routeTaskInfo->city1Latitude, $routeTaskInfo->city1Longitude);
            $vertexB = new GVertex($routeTaskInfo->cityId2, $routeTaskInfo->city2Name, $routeTaskInfo->city2Latitude, $routeTaskInfo->city2Longitude);

            // получаем стоимость задания - если стоимость перевозки не указана, то возвращаем стоимость рассчитанную по собственному тарифу
            $cost = self::_getTaskCost($routeTaskInfo, $options);
            // создаём объект RouteTask
            $task = new RouteTask($routeTaskInfo->id, $routeTaskInfo->name, $vertexA, $vertexB, $cost, $routeTaskInfo->value, $routeTaskInfo->weight, $routeTaskInfo->distance);
            array_push($list, $task);
        }

        //print_r($list);
        //exit();

        $routeTaskList = new RouteTaskList();
        $routeTaskList->addRouteTasks($list);

        //print_r($routeTaskList);

        // 5. получаем список уникальных вершин для графа - GVertex[]
        $vertices = $routeTaskList->getVertices();

        //print_r($vertices);


        // 6. получаем список городов.
        // ВАЖНО: В текущей реализации id вершины = id города
        $cityIds = array();

        foreach($vertices as $vertex)
            array_push($cityIds, $vertex->getId());

        //print_r($cityIds);

        // 7. получаем дистанцию между городами
        $distanceList = GeoRouteHelper::GetDistanceList($cityIds, $db);

        //print_r($distanceList);

        // 8. создание массива рёбер для графа - GEdge[]
        // ВАЖНО: В текущей реализации id вершины = id города
        $edges = array();
        $edgeId = 1;

        foreach($distanceList->geoRouteDistanceList as $geoDistance)
        {
            $edge = new GEdge($edgeId++, '', $geoDistance->city1Id, $geoDistance->city2Id, $geoDistance->distance);
            array_push($edges, $edge);
        }

        //print_r($edges);

        // 9. создаём граф
        $graph = new UndirectedGraph();
        $graph->init($vertices, $edges);

        //print_r(count($graph->getEdges()));

        // 10. получаем вершину, с которой начинается наш маршрут
        //print_r($options->startCityId);
        $startVertex = $vertices[$options->startCityId];

        //print_r($startVertex->getId());

        // 11. расчитываем маршрут
        $calculator = new RouteCalculator($routeTaskList, $routeRestrictions, $graph);
        $calculator->calculateRoute($startVertex);

        // 12. получаем маршрут
        if($options->buildWayBack)
        {
            $route = $calculator->getRouteWithWayBack();
        }
        else
            $route = $calculator->getRoute();

        //$output = print_r($route, true);
        //file_put_contents('D:\dump.txt', $output);


        // 13. Возвращаем рассчитанный маршрут
        return $route;
    }


    static function UpdateRoute($accountId, $userTokenId, $options, $routeData, $db)
    {
        // 1. получаем идентификатор маршрута
        $routeId = RouteHelper::GetRouteId($accountId, $userTokenId, $db);

        // 2. если маршрут отсутствует то создаём его
        if(1 > $routeId)
        {
            $routeId = RouteHelper::CreateRoute($accountId, $userTokenId, $db);
        }

        // 3. Удаляем данные маршрута
        RouteHelper::ClearRoute($routeId, $db);

        // 4. Вносим данные в маршрут
        $num = 1;

        // ... 4.1 Создаём первую запись в маршруте
        $startVertex = $routeData->getStartVertex();

        RouteHelper::CreateRoutePoint($routeId, null, $startVertex->getId(), 0, RoutePointType::StartPoint, $num++, $db);

        // ... 4.2 создаём карту cargoId к cargoSelectedId
        CargoSelectedHelper::CreateMap($accountId, $userTokenId, $db);

        // ... 4.3 получаем список рёбер маршрута - RouteEntry[]
        $routeEntries = $routeData->getEntries();

        //print_r($routes);

        // ... 4.4 обрабатываем данные каждого ребра маршрута
        $distance = 0;

        foreach($routeEntries as $routeEntry)
        {
            $edge = $routeEntry->getEdge();

            // список загруженных грузов в точке А
            $vertexATasks = $routeEntry->getCommitedTasks();

            foreach($vertexATasks as $taskA)
            {
                $cargoSelectedId = CargoSelectedHelper::GetCargoSelectedIdByCargoId($taskA->getId());
                $vertexA = $taskA->getVertexA();
                RouteHelper::CreateRoutePoint($routeId, $cargoSelectedId, $vertexA->getId(), $distance, RoutePointType::FirstPoint, $num++, $db);

                // обнуляем дистанцию - дистанция указывается, только при смене города, т.е. для 1-го задания из точки А ребра
                $distance = 0;
            }

            // для первого груза в точке B указываем дистанцию
            $distance = $edge->getDistance();

            // список выгруженных грузов в точке B
            $vertexBTasks = $routeEntry->getFulfiledTasks();

            foreach($vertexBTasks as $taskB)
            {
                $cargoSelectedId = CargoSelectedHelper::GetCargoSelectedIdByCargoId($taskB->getId());
                $vertexB = $taskB->getVertexB();
                RouteHelper::CreateRoutePoint($routeId, $cargoSelectedId, $vertexB->getId(), $distance, RoutePointType::SecondPoint, $num++, $db);

                // обнуляем дистанцию - дистанция указывается, только при смене города, т.е. для 1-го задания из точки B ребра
                $distance = 0;
            }

            //print_r($routeEntry);
        }

        // TODO при необходимости сохраняем обратный путь к началу маршрута
        if($options->buildWayBack)
        {
            // 1. сначала нужно проверить, что маршрут не содержит возвращение в начальную точку
            $startVertex = $routeData->getStartVertex();
            $endVertex = $routeData->getEndVertex();

            if($startVertex->isEqual($endVertex))
                return;

            // 2. если твозвращения нет, то добавляем ребро в маршрут
            $wayBackEntry = $routeData->getWayBackEntry();

            $edge = $wayBackEntry->getEdge();
            $distance = $edge->getDistance();

            RouteHelper::CreateRoutePoint($routeId, null, $startVertex->getId(), $distance, RoutePointType::WayBackPoint, $num, $db);
        }
    }


    static private function _getTaskCost($taskInfo, $options)
    {
        $cost = $taskInfo->cost;

        // если цена не указана, то используем стоимость рассчитанную по собственному тарифу
        if(0.01 > $cost)
        {
            $fullCost = $taskInfo->distance * $options->vehicleParams->tax;
            $costTaxWeight = ($taskInfo->weight / $options->vehicleParams->maxWeight) * $fullCost;
            $costTaxValue = ($taskInfo->value / $options->vehicleParams->maxValue) * $fullCost;

            //получаем максимальную цену исходя из того факта, что необходимо оплачивать максимально используемые грузом: грузоподьёмность или объём машины.
            $cost = max($costTaxWeight, $costTaxValue);
        }

        return $cost;
    }

}